### ISSUE TITLE
Capability Providers Point bad relative URL

### ISSUE THREAD

**Issue by mchoma** [wildscribe/wildscribe#17]
* https://wildscribe.github.io/WildFly/13.0/subsystem/elytron/filtering-key-store/index.html
* Click "key-store"
* Click "org.wildfly.security.key-store" capability link
* Click from Providers Point popup dialog "/subsystem=elytron/keystore=*"
* 404 for https://wildscribe.github.io/WildFly/13.0/subsystem/elytron/filtering-key-store/WildFly/13.0/subsystem/elytron/key-store/index.html

**Comment by bstansberry** [comment]
@mchoma This works ok for me, both with WF 13 and the WF 30 stuff at https://docs.wildfly.org/30/wildscribe/subsystem/elytron/filtering-key-store/index.html. Maybe this got fixed at some point and the WF 13 wildscribe was republished?

**Comment by mchoma** [comment]
I can confirm works for me as well now. Closing.
