### ISSUE TITLE
Include runtime model

### ISSUE THREAD

**Issue by tsabirgaliev** [wildscribe/wildscribe#7]
Include runtime model reference, e.g. /subsystem=datasources/datasource=x/TotalBlockingTime

**Comment by ctomc** [comment]
we do publish that, for example https://wildscribe.github.io/Wildfly/10.0.0.Final/deployment/index.html
but we should improve that in any case.

**Comment by tsabirgaliev** [comment]
@ctomc I probably didn't use the proper wording here. I meant the reference doesn't include properties of runtime objects, e.g. a datasource, that is created at runtime.

**Comment by ctomc** [comment]
yeah that is exactly there https://wildscribe.github.io/Wildfly/10.0.0.Final/deployment/subsystem/datasources/data-source/index.html

Just keep in mind that if CLI exposes it it is here, if not it is not present.

**Comment by ctomc** [comment]
I did however found an issue in generation of docs for some sub-resources of runtime resources. I have fix locally. new version should be published soon.

**Comment by ctomc** [comment]
we have published new version of wildscribe docs that are much improved and added lots of missing data and resources. 
Now we should consistently show all runtime resources
